// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgmibebjtylyhzqgczfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbWliZWJqdHlseWh6cWdjemZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTA2NDYsImV4cCI6MjA2MTQyNjY0Nn0.ZTQMyN6ATOUrFcSfP9IDvTCZayUSOAocggVPEfHoMt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);